spring.application.name=Spring_Security
spring.security.user.name=---------------
spring.security.user.password=------------

spring.datasource.url=-------------------------------------
spring.datasource.username=--------------
spring.datasource.password=----------
spring.datasource.driver-class-name=-----------
spring.jpa.hibernate.ddl-auto=----------
spring.jpa.show-sql=--------
server.servlet.session.cookie.same-site=-------
